channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - altair=4.1.0
  - altair_data_server=0.4.1
  - altair_viewer=0.3.0
  - bioconductor-depmap=1.8.0
  - bioconductor-deseq2=1.34.0
  - bioconductor-experimenthub=2.2.0
  - bioconductor-fgsea=1.20.0
  - click=8.0.3
  - flask=2.0.2
  - gawk=5.1.0
  - ipykernel=6.5.0
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - json5=0.9.5
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyter_server=1.11.2
  - jupyterlab=3.2.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - mageck=0.5.9.4
  - matplotlib=3.5.0
  - natsort=8.0.0
  - nodejs
  - nbformat=4
  - numpy=1.19.1
  - pandas=1.1.3
  - pillow=8.4.0
  - pip=20.2.4
  - pyyaml=5.4.1
  - r-base=4.1.1
  - r-devtools=2.4.2
  - r-dplyr=1.0.7
  - r-forcats=0.5.1
  - r-ggplot2=3.3.5
  - r-ggpolypath=0.1.0
  - r-ggridges=0.5.3
  - r-magrittr=2.0.1
  - r-mixtools=1.2.0
  - r-readr=2.1.0
  - r-robustrankaggreg=1.1
  - r-stringi=1.7.5
  - r-stringr=1.4.0
  - r-tibble=3.1.6
  - r-tidyr=1.1.4
  - r-venn=1.10
  - rpy2=3.4.5
  - scikit-learn=0.23.2
  - scipy=1.7.2
  - snakemake=6.7.0
  - statsmodels=0.13.0
  - yaml=0.2.5
  - pip:
    - clustergrammer2==0.18.0
    - jsonschema==3.2.0
    - nest-asyncio==1.5.1
    - ipywidgets==8.0.0b0
