
token: "shRNA"

### Workflow inputs

# Choose between "CRISPRi" and "shRNA/CRISPR"
screen_type: "shRNA"

start_from: "count"

inputs:
  fastq_dir: "resources/fastq/"
  bam_dir: "resources/bam/"
  count_table: "resources/count_matrices/shRNA/screen.count.txt"
  samples: "resources/metadata/shRNA/samples.txt"
  files: "resources/metadata/shRNA/files.txt"
  library: "resources/libraries/shRNA/SE_lib.csv"

### Tools config

#### MAGeCK
MAGeCK:
  MLE:
    activate: True 
    norm-method: 'total'
  RRA:
    activate: True

#### BAGEL
BAGEL:
  activate: True
  essentials: 'resources/BAGEL/shRNA/training_essentials.txt'
  nonessentials: 'resources/BAGEL/shRNA/training_nonessential.txt'


#### CRISPhieRmix
CRISPhieRmix:
  activate: 'True'
