### Workflow inputs

inputs:
  count_table: "../data/all.count.txt"
  samples: "../data/samples.txt"

### Experimental design
experimental_design:
  control: "M07e-J4"




### Tools config

#### MAGeCK MLE
MAGeCK:
  designmat: "../data/designmat.txt"
  MLE:
    norm-method: 'total'


BAGEL:
  essentials: '../data/training_essentials.txt'
  nonessential: '../data/training_nonessential.txt'
