
token: "CRISPRi"

### Workflow inputs

# Choose between "CRISPRi" and "shRNA/CRISPR"
screen_type: "CRISPRi"


inputs:
  fastq_dir: "/home/paularthur/PitViper_development/data/fastq/"
  count_table: "data/screen.count.txt"
  samples: "../data/metadata/CRISPRi/samples.txt"
  files: "../data/metadata/CRISPRi/files.txt"
  library: "../data/libraries/CRISPRi/SE_lib.csv"

### Experimental design
# experimental_design:
#   control: "M07e-J4"


### Tools config

#### MAGeCK MLE
MAGeCK:
  MLE:
    norm-method: 'total'


BAGEL:
  essentials: '../data/BAGEL/training_essentials.txt'
  nonessential: '../data/BAGEL/training_nonessential.txt'
