
token: "CRISPRi_CRISPhieRmix_FDR"

### Workflow inputs

# Choose between "CRISPRi" and "shRNA/CRISPR"
screen_type: "CRISPRi"

start_from: "fastq"

inputs:
  fastq_dir: "../data/fastq/"
  bam_dir: "../data/bam/"
  count_table: "data/CRISPRi_CRISPhieRmix_FDR/screen.count.txt"
  samples: "../data/metadata/CRISPRi/samples.txt"
  files: "../data/metadata/CRISPRi/files.txt"
  library: "../data/libraries/CRISPRi/SE_lib.csv"

### Tools config

#### MAGeCK
MAGeCK:
  MLE:
    activate: False 
    norm-method: 'total'
  RRA:
    activate: False

#### BAGEL
BAGEL:
  activate: False
  essentials: '../data/BAGEL/CRISPRi/training_essentials.txt'
  nonessentials: '../data/BAGEL/CRISPRi/training_nonessential.txt'


#### CRISPhieRmix
CRISPhieRmix:
  activate: 'True'
