
token: "CRISPRi_countFrom_bam"

### Workflow inputs

# Choose between "CRISPRi" and "shRNA/CRISPR"
screen_type: "CRISPRi"

count_from: "bam"

inputs:
  fastq_dir: "../data/fastq/"
  bam_dir: "../data/bam/"
  count_table: "data/CRISPRi_countFrom_bam/screen.count.txt"
  count_table_base_name: "data/CRISPRi_countFrom_bam/screen"
  samples: "../data/metadata/CRISPRi/samples.txt"
  files: "../data/metadata/CRISPRi/files.txt"
  library: "../data/libraries/CRISPRi/SE_lib.csv"

### Tools config

#### MAGeCK
MAGeCK:
  MLE:
    activate: True
    norm-method: 'total'
  RRA:
    activate: True

#### BAGEL
BAGEL:
  activate: False
  essentials: '../data/BAGEL/CRISPRi/training_essentials.txt'
  nonessential: '../data/BAGEL/CRISPRi/training_nonessential.txt'


#### CRISPhieRmix
CRISPhieRmix:
  activate: True
