
token: "shRNA_test0"
essential: None
### Workflow inputs

# Choose between "CRISPRi" and "shRNA/CRISPR"
screen_type: "shRNA"

count_from: "bam"

inputs:
  fastq_dir: ""
  bam_dir: "../data/bam/"
  count_table: "data/shRNA_test0/screen.count.txt"
  count_table_base_name: "data/shRNA_test0/screen"
  samples: "../data/metadata/shRNA/samples.txt"
  files: "../data/metadata/shRNA/files.txt"
  library: "../data/libraries/shRNA/sh_epi_lib.csv"

### Tools config

#### MAGeCK
MAGeCK:
  MLE:
    activate: False
    norm-method: 'total'
  RRA:
    activate: False

#### BAGEL
BAGEL:
  activate: False
  essentials: '../data/BAGEL/training_essentials.txt'
  nonessential: '../data/BAGEL/training_nonessential.txt'


#### CRISPhieRmix
CRISPhieRmix:
  activate: True
