
token: "shRNA"

### Workflow inputs

# Choose between "CRISPRi" and "shRNA/CRISPR"
screen_type: "shRNA"

start_from: "count"

inputs:
  fastq_dir: "../data/fastq/"
  bam_dir: "../data/bam/"
  count_table: "../data/count_matrices/shRNA/screen.count.txt"
  samples: "../data/metadata/shRNA/samples.txt"
  files: "../data/metadata/shRNA/files.txt"
  library: "../data/libraries/shRNA/SE_lib.csv"

### Tools config

#### MAGeCK
MAGeCK:
  MLE:
    activate: True 
    norm-method: 'total'
  RRA:
    activate: True

#### BAGEL
BAGEL:
  activate: True
  essentials: '../data/BAGEL/shRNA/training_essentials.txt'
  nonessentials: '../data/BAGEL/shRNA/training_nonessential.txt'


#### CRISPhieRmix
CRISPhieRmix:
  activate: 'True'
