bagel_activate: 'False'
count_table_file: resources/test_env/all.count.txt
crisphiermix_activate: 'True'
essentials: ''
filtering_activate: 'True'
gsea_activate: 'True'
library_file: ''
mageck_count_N: 'False'
mageck_count_all_align: 'False'
mageck_count_length: '20'
mageck_count_normalization: total
mageck_count_pdf: 'False'
mageck_count_rev_comp: 'False'
mageck_mle_activate: 'True'
mageck_mle_adj: fdr
mageck_mle_mean_var: '0'
mageck_mle_normalization: total
mageck_mle_outliers: 'False'
mageck_mle_perm_N: '2'
mageck_mle_perm_all: 'False'
mageck_rra_LFC: median
mageck_rra_activate: 'True'
mageck_rra_adj: fdr
mageck_rra_count_min: '0'
mageck_rra_criteria: neg
mageck_rra_pthreshold: '0.25'
mageck_rra_remove: both
nonessentials: ''
normalized_count_table: resources/test_env/screen.count_normalized.txt
screen_type: is_gene
start_from: count
token: test_env
tsv_file: resources/test_env/design.tsv
