filtering_method:
  activate: 'True'
GSEA-like_method:
  activate: 'True'
BAGEL:
  activate: 'True'
  essentials: "resources/BAGEL/shRNA/training_essentials.txt"
  nonessentials: "resources/BAGEL/shRNA/training_nonessential.txt"
CRISPhieRmix:
  activate: 'True'
MAGeCK:
  MLE:
    activate: 'True'
    norm-method: total
  RRA:
    activate: 'True'
inputs:
  count_table: screen.count.txt
  # normalized_count_table: screen.count_normalized.txt
  library: resources/libraries/shRNA/SE_lib_final.tab
  tsv: resources/metadata/shRNA/input.tsv
token: shRNA
