BAGEL:
  activate: 'False'
  essentials: null
  nonessentials: null
CRISPhieRmix:
  activate: 'True'
MAGeCK:
  MLE:
    activate: 'True'
    norm-method: total
  RRA:
    activate: 'True'
inputs:
  count_table: results/shRNA/screen.count.txt
  library: resources/libraries/shRNA/SE_lib_final.tab
  tsv: resources/metadata/shRNA/input.tsv
token: shRNA
